### ISSUE TITLE
Do we have retry parameter while comparing screenshot? 

### ISSUE THREAD

**Issue by tausif29** [odai-alali/cypress-odiff#12]
Do we have `retry` functionality while comparing the screenshot? We should have feature for retry while taking the screenshot,
Could you please introduce a new parameter as `retry` under `compareOptions`  like below:

```
addCompareScreenshotCommand({
    pluginOptions: {
        customSnapshotsDir: "cypress\\snapshots"
    },
    compareOptions:{
        threshold:0.3
        retry: 2
    }
   
});
```

**Comment by odai-alali** [comment]
You can use [Cypress Retires](https://docs.cypress.io/guides/guides/test-retries) for that.
