### ISSUE TITLE
Update peer dependencies related Cypress 

### ISSUE THREAD

**Issue by MykolaKozub** [odai-alali/cypress-odiff#3]
Right now the peerDependencies lists

"peerDependencies": {
"cypress": "10.0.3"
}
so there is a dependency warning if you are using a newer major version of cypress 10.7.0
I would propose changing it to ^n if there are no issues.

thanks so much!

**Comment by odai-alali** [comment]
This makes sense :)

I will take care of it tomorrow. Thanks for the feedback.
