### ISSUE TITLE
How to set the threshold while comparing the screenshot

### ISSUE THREAD

**Issue by tausif29** [odai-alali/cypress-odiff#5]
It works fine for me but my tests are failing with minor difference, Is there anyway I can define the threshold so it can ignore the some pixel difference while comparing the snapshot?

**Comment by odai-alali** [comment]
Try to set `threshold` under `compareOptions`. `compareOptions` will be passed to ODiff when executing the compare.

see https://github.com/odai-alali/cypress-odiff#options

**Comment by tausif29** [comment]
It worked, Thanks..!
