### ISSUE TITLE
How do I integrate `.diff` screenshot with the cucumber report

### ISSUE THREAD

**Issue by tausif29** [odai-alali/cypress-odiff#7]
I am using cypress10 with cucumber hence I use `multiple-cucumber-html-reporter` , 
When there is difference between actual and expected image, it just shows the error like `Screenshots does not match. 263553 pixels difference (29.1049943403%)` and attach the actual screenshot.

I also want to attach the `.diff` screenshot with report.

Is there anyway we can attach the failing screenshot with `multiple-cucumber-html-reporter` ?

Below is my `package.json` & `cypress.config.js`

**package.json**
![image](https://user-images.githubusercontent.com/39052801/210311692-9e13262c-06b3-4865-afcd-38dfff1ab903.png)

**cypress.config.js**
![image](https://user-images.githubusercontent.com/39052801/210311595-baf0e308-df2e-49c4-bad8-eb9ede6c6c57.png)

**Comment by odai-alali** [comment]
I would like to help, but I'm not familiar with cucumber API and this issue seems to be out of this repository's scope. However, if you were able to find a solution that requires changes to `cypress-odiff` plugin, let me know please.
