### ISSUE TITLE
Why does system appends additional path with the configured path of the screenshot?

### ISSUE THREAD

**Issue by tausif29** [odai-alali/cypress-odiff#8]
![image](https://user-images.githubusercontent.com/39052801/210774720-032045ec-019e-4ef0-97b0-98a0164d2871.png)

As per above screenshot, I have set the directory for the snapshot as `customSnapshotsDir: "cypress/snapshots"`

But when system adds additional sub-folders into that directory like `\cypress\e2e\features` and then stores the the screenshot in particular test folder.

![image](https://user-images.githubusercontent.com/39052801/210776446-297a3e7f-f6b9-47f0-b9cc-cef0bc38b05d.png)

I don't want these additional sub-folders:  `\cypress\e2e\features`  into the configured directory.

All the screenshot should be stored like `\cypress\snapshots\test1.feature\<test-screenshots>` 

Is there anyway I can store the screenshot directly into the configured directory as per configuration under `command.js`

**Comment by odai-alali** [comment]
The path prefix `/cypress/e2e/` should be omitted. See https://github.com/odai-alali/cypress-odiff/blob/main/src/command.ts#L26

And I see that you are using windows, where path separator is `\` not `/`. This needs to be supported. I'll try to support this as soon as possible.
